name: plant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  appwrite: ^15.0.0
  awesome_extensions: ^2.0.21
  camerawesome: ^2.3.0
  envied: ^1.1.1
  equatable: ^2.0.7
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  loader_overlay: ^5.0.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  envied_generator: ^1.1.1
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
  assets:
  - assets/images/
